test without yocto cache
Signed-off-by: Yongjoo Ahn <yongjoo1.ahn@samsung.com>

diff --git a/.github/workflows/yocto.yml b/.github/workflows/yocto.yml
--- a/.github/workflows/yocto.yml
+++ b/.github/workflows/yocto.yml
@@ -1,10 +1,11 @@
-name: Build test / Yocto 5.0.3 (kirkstone-5.0.3)
+name: Build test / Yocto-5.0.3 (kirkstone-5.0.3)
 
 on:
   pull_request:
     branches: [ main ]
-  push:
-    branches: [ main ]
+
+  # Allow manually triggering the workflow
+  workflow_dispatch:
 
 jobs:
   build:
@@ -24,34 +25,26 @@ jobs:
       ## prevent permission error
       run: sudo mkdir --mode a=rwx --parents /var/cache/yocto
 
-    - name: get date
-      id: get-date
-      run: |
-        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
-
-    - name: cache yocto sstate and downloads
-      uses: actions/cache@v4
+    - name: restore yocto sstate and downloads cache
+      if: env.rebuild == '1'
+      uses: actions/cache/restore@v4
       with:
         path: |
           /var/cache/yocto/downloads
           /var/cache/yocto/sstate-cache
           /var/cache/yocto/persistent
-        key: yocto-cache-yocto-5.0.3-${{ steps.get-date.outputs.date }}
-        restore-keys: |
-          yocto-cache-yocto-
+        key: yocto-cache-yocto-5.0.3
 
-    ## @todo Make cache works (daily update cache on main branch / restore the cache on each PR (not saving))
-    - name: Prepare build
-      # if: env.rebuild == '1'
+    - name: build
+      if: env.rebuild == '1'
       run: |
         echo "::group::apt-get install"
         sudo apt-get update
         sudo apt install gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 python3-subunit zstd liblz4-tool file locales libacl1
         pip install websockets
-        echo "::endgroup::"
-        echo "::group::Locale Setup"
         sudo locale-gen en_US.UTF-8
         echo "::endgroup::"
+
         echo "::group::Prepare poky and meta-neural-network"
         git clone git://git.yoctoproject.org/poky -b yocto-5.0.3 && cd poky
         git clone https://github.com/anyj0527/meta-neural-network -b scarthgap
@@ -60,6 +53,7 @@ jobs:
         source oe-init-build-env
         bitbake-layers add-layer ../meta-neural-network
         echo "::endgroup::"
+
         echo "::group::Set local.conf"
         echo 'DL_DIR = "/var/cache/yocto/downloads"' >> conf/local.conf
         echo 'BB_GENERATE_MIRROR_TARBALLS = "1"' >> conf/local.conf
@@ -69,20 +63,27 @@ jobs:
         echo 'BB_HASHSERVE_UPSTREAM = "wss://hashserv.yoctoproject.org/ws"' >> conf/local.conf
         echo 'SSTATE_MIRRORS ?= "file://.* http://cdn.jsdelivr.net/yocto/sstate/all/PATH;downloadfilename=PATH"' >> conf/local.conf
         echo 'PERSISTENT_DIR="/var/cache/yocto/persistent"' >> conf/local.conf
+        echo "::endgroup::"
+
+        echo "::group::Do setscene-only task and disregard its error"
         bitbake --setscene-only nnstreamer || true
+        echo "::endgroup::"
+
+        echo "::group::Build nnstreamer"
         bitbake --skip-setscene nnstreamer
         echo "::endgroup::"
-    # - name: Build
-    #   # if: env.rebuild == '1'
-    #   run: |
-    #     bitbake nnstreamer
 
-    - name: save yocto cache
+        echo "::group::Cat build log"
+        cat tmp/work/core2-64-poky-linux/nnstreamer/*/temp/log.do_configure || true
+        cat tmp/work/core2-64-poky-linux/nnstreamer/*/temp/log.do_compile || true
+        echo "::endgroup::"
+
+    - name: save yocto cache (main branch only)
       uses: actions/cache/save@v4
-      if: always()
+      if: always() && github.ref == 'refs/heads/main'
       with:
         path: |
           /var/cache/yocto/downloads
           /var/cache/yocto/sstate-cache
           /var/cache/yocto/persistent
-        key: yocto-cache-yocto-5.0.3-${{ steps.get-date.outputs.date }}
+        key: yocto-cache-yocto-5.0.3
